version: '3.9'
services:
  node-api:
    image: dymafr/cicd-projet6-node-api
    ports:
      - '3000:80'
  frontend:
    image: dymafr/cicd-projet6-frontend
    ports:
      - '80:80'
  cypress:
    image: cypress/included
    working_dir: /e2e
    environment:
      - NO_COLOR=1
    volumes:
      - ./frontend:/e2e
    entrypoint: cypress run --config baseUrl=http://frontend --headless --browser chrome -C cypress.config.js
    depends_on:
      - frontend
      - node-api
