version: '3.9'

services:
  node-api:
    image: dymafr/cicd-projet6-node-api
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  frontend:
    image: dymafr/cicd-projet6-frontend
    ports:
      - target: 80
        published: 80
    restart: always
